source "https://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'bicvalidator',:git => 'https://github.com/olafkaderka/bicvalidator.git', :branch => 'master'
# Specify your gem's dependencies in bicvalidator.gemspec
gemspec
